backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects-page'
    create: true
    slug: '{{project}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'project-page' }
      - { label: 'Project', name: 'project', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'End Date', name: 'endDate', widget: 'datetime' }
      - { label: 'Icon', name: 'icon', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Team', name: 'team', widget: 'list' }
      - { label: 'Organization', name: 'organization', widget: 'string' }
      - { label: 'Project Color', name: 'projectColor', widget: 'string' }
      - { label: 'Mission', name: 'mission', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
